services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Server/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}        # например http://0.0.0.0:8080
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      Jwt__Key: ${Jwt__Key}
      Jwt__Audience: ${Jwt__Audience}
      Jwt__Issuer: ${Jwt__Issuer}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - avatars:/app/wwwroot/avatars            # API пишет сюда
    expose:
      - "8080"                                   # доступно ТОЛЬКО в сети докера

  web:
    build:
      context: ./WebClient
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE}
        VITE_HUB_URL: ${VITE_HUB_URL}
    environment:
      - DOMAIN=${DOMAIN}
    depends_on: [ api ]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.https.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt


  certbot:
    image: certbot/certbot:latest
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: sh
    command: -c 'sleep 5; certbot certonly --webroot -w /var/www/certbot -d ${DOMAIN} -d www.${DOMAIN} --email ${EMAIL} --agree-tos --no-eff-email --rsa-key-size 4096 --non-interactive && crond -f'

volumes:
  letsencrypt:
  certbot-www:
  pgdata:
  avatars:
